// swift-tools-version: 6.2
// HephaestusBridge: Swift FFI shim between the Rust hephaestus-bridge crate
// and Apple's containerization framework.
//
// Two targets:
//   * CHephaestusBridge — public C headers generated by cbindgen; consumed by
//     Swift via a module map to get identical struct layouts on both sides.
//   * HephaestusBridge — Swift implementation of the @_cdecl FFI exports.

import PackageDescription

let package = Package(
    name: "HephaestusBridge",
    platforms: [.macOS("15")],
    products: [
        .library(
            name: "HephaestusBridge",
            type: .static,
            targets: ["HephaestusBridge"]
        )
    ],
    dependencies: [
        // Pin to the latest released tag at the time of writing; bump as needed.
        .package(
            url: "https://github.com/apple/containerization.git",
            exact: "0.30.1"
        )
    ],
    targets: [
        .target(
            name: "CHephaestusBridge",
            path: "Sources/CHephaestusBridge",
            publicHeadersPath: "include"
        ),
        .target(
            name: "HephaestusBridge",
            dependencies: [
                "CHephaestusBridge",
                .product(name: "Containerization", package: "containerization"),
                .product(name: "ContainerizationArchive", package: "containerization"),
                .product(name: "ContainerizationEXT4", package: "containerization"),
            ],
            path: "Sources/HephaestusBridge"
        ),
    ]
)
