// Swift-side implementation of the hephaestus FFI. Types shared with Rust
// (HbVmConfig, HbStatus, HbVm) come from the CHephaestusBridge module, whose
// header is generated by cbindgen at Rust build time.

import CHephaestusBridge
import Containerization
import ContainerizationArchive
import ContainerizationEXT4
import ContainerizationError
import ContainerizationExtras
import ContainerizationOS
import Dispatch
import Foundation

// =============================================================================
// hb_ping — M0 smoke test, kept for the CLI `ping` subcommand.
// =============================================================================

nonisolated(unsafe) private let pongPtr: UnsafePointer<CChar> = {
    let s = "pong"
    let buf = UnsafeMutablePointer<CChar>.allocate(capacity: s.utf8.count + 1)
    _ = s.withCString { strcpy(buf, $0) }
    return UnsafePointer(buf)
}()

@_cdecl("hb_ping")
public func hb_ping() -> UnsafePointer<CChar> {
    return pongPtr
}

// =============================================================================
// Error / status helpers.
// =============================================================================

enum Status {
    static let ok: Int32 = 0
    static let invalidArgument: Int32 = 1
    static let swiftError: Int32 = 2
}

/// Duplicate a Swift String onto the C heap as a NUL-terminated CChar array.
/// Callers (Rust) release via `hb_string_free`.
private func cstrdup(_ s: String) -> UnsafeMutablePointer<CChar> {
    let bytes = Array(s.utf8) + [0]
    let buf = UnsafeMutablePointer<CChar>.allocate(capacity: bytes.count)
    bytes.withUnsafeBufferPointer { src in
        buf.withMemoryRebound(to: UInt8.self, capacity: bytes.count) { dst in
            dst.update(from: src.baseAddress!, count: bytes.count)
        }
    }
    return buf
}

func writeError(
    _ outErr: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?,
    _ message: String
) {
    guard let outErr else { return }
    outErr.pointee = cstrdup(message)
}

/// Format a caught Swift `Error` into something friendlier than the default
/// stringification. Adds an action-oriented hint for recognized VZ codes and
/// drops the noisy `Error Domain=... Code=N UserInfo={…}` prefix.
func formatError(_ error: Error) -> String {
    let ns = error as NSError
    guard ns.domain == "VZErrorDomain" else {
        return "\(error)"
    }
    var parts: [String] = [ns.localizedDescription]
    // Foundation often embeds the reason inside localizedDescription already
    // (as ". Reason: …") — only append separately when it's meaningfully new.
    if let reason = ns.userInfo[NSLocalizedFailureReasonErrorKey] as? String,
       !ns.localizedDescription.contains(reason) {
        parts.append(reason)
    }
    if let hint = vzErrorHint(code: ns.code) {
        parts.append("hint: \(hint)")
    }
    return parts.joined(separator: " — ")
}

private func vzErrorHint(code: Int) -> String? {
    // Mirrors VZErrorCode values documented at
    // https://developer.apple.com/documentation/virtualization/vzerror/code
    switch code {
    case 1:  return "VZ internal error — check kernel and disk image validity"
    case 2:  return "binary is missing the com.apple.security.virtualization entitlement"
    case 3:  return "VM is in the wrong state for this operation"
    case 4:  return "invalid state transition requested"
    case 5:  return "invalid disk image — is the path a real ext4 block device?"
    case 6:  return "network error"
    case 7:  return "out of disk space"
    case 8:  return "operation cancelled"
    case 9:  return "operation not supported on this platform / macOS version"
    case 10: return "save (snapshot) failed"
    case 11: return "restore (snapshot) failed"
    case 12: return "device not found"
    default: return nil
    }
}

// =============================================================================
// Async-to-sync bridge: runs an async Swift closure and blocks the caller
// until it completes, returning its result or throwing its error.
// =============================================================================

private final class ResultBox<T>: @unchecked Sendable {
    var value: Result<T, Error>?
}

private func runSync<T: Sendable>(
    _ body: @Sendable @escaping () async throws -> T
) throws -> T {
    let semaphore = DispatchSemaphore(value: 0)
    let box = ResultBox<T>()
    // Hop onto a pthread queue before spawning the Task so the Swift
    // cooperative pool isn't trying to drain a blocked-caller scenario
    // from the same thread the async work gets scheduled on. Then spawn
    // an async Task from there; NIO's own EventLoopGroup threads run
    // happily alongside.
    DispatchQueue.global(qos: .userInitiated).async {
        Task {
            do {
                box.value = .success(try await body())
            } catch {
                box.value = .failure(error)
            }
            semaphore.signal()
        }
    }
    semaphore.wait()
    return try box.value!.get()
}

// =============================================================================
// CallbackWriter: implements Containerization's `Writer` protocol by
// forwarding each chunk to a C callback pointer supplied by Rust.
// =============================================================================

private final class CallbackWriter: Writer, @unchecked Sendable {
    let callback:
        @convention(c) (UnsafeMutableRawPointer?, UnsafePointer<UInt8>?, UInt) -> Void
    let userdata: UnsafeMutableRawPointer?

    init(
        callback: @escaping @convention(c) (
            UnsafeMutableRawPointer?, UnsafePointer<UInt8>?, UInt
        ) -> Void,
        userdata: UnsafeMutableRawPointer?
    ) {
        self.callback = callback
        self.userdata = userdata
    }

    func write(_ data: Data) throws {
        guard !data.isEmpty else { return }
        data.withUnsafeBytes { buf in
            guard let base = buf.baseAddress?.assumingMemoryBound(to: UInt8.self) else {
                return
            }
            callback(userdata, base, UInt(buf.count))
        }
    }

    func close() throws {
        // No-op: Rust owns the sink's lifetime.
    }
}

// =============================================================================
// VmHandle — the Swift-side object Rust owns via an opaque HbVm pointer.
//
// Holds strong refs to the container and everything it transitively needs so
// nothing is freed while Rust still has the handle.
// =============================================================================

private final class VmHandle: @unchecked Sendable {
    let container: LinuxContainer
    /// Host's controlling terminal, retained when TTY mode is requested so
    /// we can restore its termios attributes when the handle is freed.
    let terminal: Terminal?

    init(container: LinuxContainer, terminal: Terminal?) {
        self.container = container
        self.terminal = terminal
    }

    deinit {
        // Belt-and-suspenders: if the caller missed a stop() we still want
        // the user's shell back from raw mode.
        terminal?.tryReset()
    }
}

// =============================================================================
// Construction: hb_vm_new
// =============================================================================

@_cdecl("hb_vm_new")
public func hb_vm_new(
    config: UnsafePointer<HbVmConfig>?,
    outVm: UnsafeMutablePointer<UnsafeMutablePointer<HbVm>?>?,
    outErr: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?
) -> Int32 {
    guard let config, let outVm else {
        writeError(outErr, "hb_vm_new: null required out-param")
        return Status.invalidArgument
    }

    let cfg = config.pointee
    guard
        let idCstr = cfg.id,
        let kernelCstr = cfg.kernel_path,
        let initfsCstr = cfg.initfs_path,
        let rootfsCstr = cfg.rootfs_path
    else {
        writeError(outErr, "HbVmConfig contains a null string field")
        return Status.invalidArgument
    }

    let id = String(cString: idCstr)
    let kernelPath = String(cString: kernelCstr)
    let initfsPath = String(cString: initfsCstr)
    let rootfsPath = String(cString: rootfsCstr)
    let cwd = cfg.cwd.map { String(cString: $0) }
    let arguments = collectArgv(cfg.argv)

    do {
        let kernel = Kernel(
            path: URL(fileURLWithPath: kernelPath),
            platform: .linuxArm
        )

        let initfs = Mount.block(
            format: "ext4",
            source: initfsPath,
            destination: "/"
        )

        let rootfs = Mount.block(
            format: "ext4",
            source: rootfsPath,
            destination: "/"
        )

        let vmm = VZVirtualMachineManager(
            kernel: kernel,
            initialFilesystem: initfs
        )

        let stdoutWriter: Writer? = cfg.on_stdout.map {
            CallbackWriter(callback: $0, userdata: cfg.stdio_userdata)
        }
        let stderrWriter: Writer? = cfg.on_stderr.map {
            CallbackWriter(callback: $0, userdata: cfg.stdio_userdata)
        }

        // TTY mode: when requested, grab the host's controlling terminal so
        // we can wire both stdio and pty behavior. The actual `setraw()`
        // happens at start time (in hb_vm_start) so that if construction
        // errors out the user's terminal is never disturbed.
        let terminal: Terminal? = cfg.enable_tty ? try Terminal.current : nil

        // Send the guest's serial console to a file so we can tail it for
        // boot diagnostics when things go wrong inside the VM.
        let bootLogURL = URL(
            fileURLWithPath: NSTemporaryDirectory(), isDirectory: true
        ).appendingPathComponent("hephaestus-\(id).bootlog")

        let container = try LinuxContainer(
            id,
            rootfs: rootfs,
            vmm: vmm
        ) { c in
            if !arguments.isEmpty {
                c.process.arguments = arguments
            }
            if let cwd {
                c.process.workingDirectory = cwd
            }
            if cfg.cpus > 0 {
                c.cpus = Int(cfg.cpus)
            }
            if cfg.memory_mib > 0 {
                c.memoryInBytes = cfg.memory_mib * (1 << 20)
            }
            if let terminal {
                // setTerminalIO sets terminal=true and wires stdin+stdout
                // through the pty. Containerization validates that stderr is
                // *not* set in that mode (stderr is merged into the pty
                // stream), so we leave it nil.
                c.process.setTerminalIO(terminal: terminal)
            } else {
                c.process.stdout = stdoutWriter
                c.process.stderr = stderrWriter
            }
            c.bootLog = BootLog.file(path: bootLogURL)
            if cfg.enable_networking {
                // Use VZ's built-in NAT (VZNATNetworkDeviceAttachment) via
                // NATInterface. This only requires com.apple.security.virtualization
                // — unlike VmnetNetwork which needs the restricted
                // com.apple.vm.networking entitlement (incompatible with
                // ad-hoc signing). VZ's NAT subnet is fixed at 192.168.64.0/24;
                // the last octet is supplied by the caller (hashed from the
                // VM id by default) so concurrent VMs don't collide.
                let subnet = try CIDRv4("192.168.64.\(cfg.network_ip_octet)/24")
                let gateway = try IPv4Address("192.168.64.1")
                c.interfaces = [
                    NATInterface(ipv4Address: subnet, ipv4Gateway: gateway)
                ]
                c.dns = DNS(nameservers: [gateway.description])
            }
        }

        let handle = VmHandle(container: container, terminal: terminal)
        let opaque = Unmanaged.passRetained(handle).toOpaque()
        outVm.pointee = opaque.assumingMemoryBound(to: HbVm.self)
        outErr?.pointee = nil
        return Status.ok
    } catch {
        writeError(outErr, formatError(error))
        return Status.swiftError
    }
}

private func collectArgv(_ raw: UnsafePointer<UnsafePointer<CChar>?>?) -> [String] {
    guard let raw else { return [] }
    var out: [String] = []
    var i = 0
    while let ptr = raw[i] {
        out.append(String(cString: ptr))
        i += 1
    }
    return out
}

// =============================================================================
// Lifecycle: hb_vm_create / hb_vm_start / hb_vm_wait / hb_vm_stop
// =============================================================================

@_cdecl("hb_vm_create")
public func hb_vm_create(
    vm: UnsafeMutablePointer<HbVm>?,
    outErr: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?
) -> Int32 {
    guard let handle = borrow(vm, outErr) else { return Status.invalidArgument }
    do {
        try runSync { try await handle.container.create() }
        outErr?.pointee = nil
        return Status.ok
    } catch {
        writeError(outErr, formatError(error))
        return Status.swiftError
    }
}

@_cdecl("hb_vm_start")
public func hb_vm_start(
    vm: UnsafeMutablePointer<HbVm>?,
    outErr: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?
) -> Int32 {
    guard let handle = borrow(vm, outErr) else { return Status.invalidArgument }
    do {
        // In TTY mode we take over the host terminal just before starting
        // the guest. Any failure below should still restore cooked mode,
        // which `deinit` guarantees; this path gives prompt recovery on
        // the happy path via hb_vm_stop.
        try handle.terminal?.setraw()
        try runSync { try await handle.container.start() }
        outErr?.pointee = nil
        return Status.ok
    } catch {
        handle.terminal?.tryReset()
        writeError(outErr, formatError(error))
        return Status.swiftError
    }
}

@_cdecl("hb_vm_wait")
public func hb_vm_wait(
    vm: UnsafeMutablePointer<HbVm>?,
    outExit: UnsafeMutablePointer<Int32>?,
    outErr: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?
) -> Int32 {
    guard let handle = borrow(vm, outErr) else { return Status.invalidArgument }
    do {
        let status = try runSync { try await handle.container.wait() }
        outExit?.pointee = Int32(status.exitCode)
        outErr?.pointee = nil
        return Status.ok
    } catch {
        writeError(outErr, formatError(error))
        return Status.swiftError
    }
}

@_cdecl("hb_vm_stop")
public func hb_vm_stop(
    vm: UnsafeMutablePointer<HbVm>?,
    outErr: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?
) -> Int32 {
    guard let handle = borrow(vm, outErr) else { return Status.invalidArgument }
    do {
        try runSync { try await handle.container.stop() }
        handle.terminal?.tryReset()
        outErr?.pointee = nil
        return Status.ok
    } catch {
        handle.terminal?.tryReset()
        writeError(outErr, formatError(error))
        return Status.swiftError
    }
}

// =============================================================================
// Memory management.
// =============================================================================

@_cdecl("hb_vm_free")
public func hb_vm_free(vm: UnsafeMutablePointer<HbVm>?) {
    guard let vm else { return }
    let opaque = UnsafeMutableRawPointer(vm)
    Unmanaged<VmHandle>.fromOpaque(opaque).release()
}

@_cdecl("hb_string_free")
public func hb_string_free(s: UnsafeMutablePointer<CChar>?) {
    guard let s else { return }
    s.deallocate()
}

/// Borrow a `VmHandle` from an opaque `*mut HbVm` without consuming the retain.
private func borrow(
    _ vm: UnsafeMutablePointer<HbVm>?,
    _ outErr: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?
) -> VmHandle? {
    guard let vm else {
        writeError(outErr, "null VM handle")
        return nil
    }
    let opaque = UnsafeMutableRawPointer(vm)
    return Unmanaged<VmHandle>.fromOpaque(opaque).takeUnretainedValue()
}

// =============================================================================
// hb_rootfs_from_tar — build an ext4 block device from a tar archive.
// =============================================================================

@_cdecl("hb_rootfs_from_tar")
public func hb_rootfs_from_tar(
    tarPath: UnsafePointer<CChar>?,
    outPath: UnsafePointer<CChar>?,
    blockSizeMib: UInt64,
    compressionCode: UInt32,
    outErr: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?
) -> Int32 {
    guard let tarPath, let outPath else {
        writeError(outErr, "null path")
        return Status.invalidArgument
    }

    let tar = URL(fileURLWithPath: String(cString: tarPath))
    let out = URL(fileURLWithPath: String(cString: outPath))

    let filter: ContainerizationArchive.Filter
    switch compressionCode {
    case 0: filter = .none
    case 1: filter = .gzip
    case 2: filter = .zstd
    default:
        writeError(outErr, "unknown compression code \(compressionCode)")
        return Status.invalidArgument
    }

    let sizeInBytes: UInt64 = (blockSizeMib == 0 ? 512 : blockSizeMib) * (1 << 20)

    do {
        // EXT4Unpacker isn't Sendable, so construct and use it inside the
        // closure rather than capturing it across the actor hop.
        try runSync {
            let unpacker = EXT4Unpacker(blockSizeInBytes: sizeInBytes)
            try await unpacker.unpack(archive: tar, compression: filter, at: out)
        }
        outErr?.pointee = nil
        return Status.ok
    } catch {
        writeError(outErr, formatError(error))
        return Status.swiftError
    }
}
