// Swift-side implementation of the hephaestus FFI. Types shared with Rust
// (HbVmConfig, HbStatus, HbVm) come from the CHephaestusBridge module, whose
// header is generated by cbindgen at Rust build time.

import CHephaestusBridge
import Containerization
import Foundation

// =============================================================================
// hb_ping — M0 smoke test, kept for the CLI `ping` subcommand.
// =============================================================================

nonisolated(unsafe) private let pongPtr: UnsafePointer<CChar> = {
    let s = "pong"
    let buf = UnsafeMutablePointer<CChar>.allocate(capacity: s.utf8.count + 1)
    _ = s.withCString { strcpy(buf, $0) }
    return UnsafePointer(buf)
}()

@_cdecl("hb_ping")
public func hb_ping() -> UnsafePointer<CChar> {
    return pongPtr
}

// =============================================================================
// VM construction — M1 exit criteria: construct and drop without leaks.
//
// We wrap the constructed LinuxContainer in a Swift class so we can retain
// multiple strong references (the container, the VMM, the kernel) under one
// opaque pointer. Rust owns one retain; hb_vm_free releases it.
// =============================================================================

/// Status codes must stay in lockstep with the Rust `HbStatus` enum.
private enum Status {
    static let ok: Int32 = 0
    static let invalidArgument: Int32 = 1
    static let swiftError: Int32 = 2
}

private final class VmHandle: @unchecked Sendable {
    let container: LinuxContainer

    init(container: LinuxContainer) {
        self.container = container
    }
}

@_cdecl("hb_vm_new")
public func hb_vm_new(
    config: UnsafePointer<HbVmConfig>?,
    outVm: UnsafeMutablePointer<UnsafeMutablePointer<HbVm>?>?,
    outErr: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?
) -> Int32 {
    guard let config, let outVm, let outErr else {
        return Status.invalidArgument
    }

    let cfg = config.pointee
    guard
        let idCstr = cfg.id,
        let kernelCstr = cfg.kernel_path,
        let rootfsCstr = cfg.rootfs_path
    else {
        writeError(outErr, "HbVmConfig contains a null string field")
        return Status.invalidArgument
    }

    let id = String(cString: idCstr)
    let kernelPath = String(cString: kernelCstr)
    let rootfsPath = String(cString: rootfsCstr)

    do {
        let kernel = Kernel(
            path: URL(fileURLWithPath: kernelPath),
            platform: .linuxArm
        )

        let rootfs = Mount.block(
            format: "ext4",
            source: rootfsPath,
            destination: "/"
        )

        // M1 placeholder: the initialFilesystem is required by
        // VZVirtualMachineManager but only consumed at VM start. We reuse the
        // rootfs path to satisfy construction; M2 will plumb vminitd's
        // actual init ramdisk.
        let initialFs = Mount.block(
            format: "ext4",
            source: rootfsPath,
            destination: "/"
        )

        let vmm = VZVirtualMachineManager(
            kernel: kernel,
            initialFilesystem: initialFs
        )

        let container = try LinuxContainer(
            id,
            rootfs: rootfs,
            vmm: vmm,
            configuration: { _ in }
        )

        let handle = VmHandle(container: container)
        let opaque = Unmanaged.passRetained(handle).toOpaque()
        outVm.pointee = opaque.assumingMemoryBound(to: HbVm.self)
        outErr.pointee = nil
        return Status.ok
    } catch {
        writeError(outErr, "\(error)")
        return Status.swiftError
    }
}

@_cdecl("hb_vm_free")
public func hb_vm_free(vm: UnsafeMutablePointer<HbVm>?) {
    guard let vm else { return }
    let opaque = UnsafeMutableRawPointer(vm)
    Unmanaged<VmHandle>.fromOpaque(opaque).release()
}

@_cdecl("hb_string_free")
public func hb_string_free(s: UnsafeMutablePointer<CChar>?) {
    guard let s else { return }
    // Paired with the allocate() in writeError below.
    s.deallocate()
}

private func writeError(
    _ outErr: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>,
    _ message: String
) {
    let bytes = Array(message.utf8) + [0]
    let buf = UnsafeMutablePointer<CChar>.allocate(capacity: bytes.count)
    bytes.withUnsafeBufferPointer { src in
        buf.withMemoryRebound(to: UInt8.self, capacity: bytes.count) { dst in
            dst.update(from: src.baseAddress!, count: bytes.count)
        }
    }
    outErr.pointee = buf
}
